// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svgkbpbcpgaawpqbeedr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Z2ticGJjcGdhYXdwcWJlZWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTM3NDIsImV4cCI6MjA2ODkyOTc0Mn0.qQ_hWzmUVXloW3rMx2XpUBi-0bQD1gOacGgQjlWdjsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});